import * as Taro from '@tarojs/taro';
import { BoundingClientRectCallback, RequestPaymentOption, ShowModalOption, AuthorizeScope, Loading } from './types';
export declare const push: (url: string, params?: Record<string, any>) => Promise<TaroGeneral.CallbackResult>;
export declare const replace: (url: string, params?: Record<string, any>) => Promise<TaroGeneral.CallbackResult>;
export declare const reLaunch: (url: string, params?: Record<string, any>) => Promise<TaroGeneral.CallbackResult>;
export declare const switchTab: (url: string, params?: Record<string, any>) => Promise<TaroGeneral.CallbackResult>;
export declare const back: (delta?: number, delay?: number) => Promise<TaroGeneral.CallbackResult>;
export declare const getPageNum: () => number;
export declare const toast: (title: string, duration?: number) => Promise<TaroGeneral.CallbackResult>;
export declare const loading: ({ title, delay, timeout, onTimeout }?: Partial<Loading>) => () => Promise<void>;
export declare const alert: (content: string | string[], title?: string, option?: ShowModalOption) => Promise<never>;
export declare const confirm: (content: string | string[], title?: string, option?: ShowModalOption) => Promise<never>;
export declare const getStorage: (key: string) => Promise<any>;
export declare const setStorage: (key: string, params: any) => Promise<TaroGeneral.CallbackResult>;
export declare const removeStorage: (keys?: string | string[] | "*") => Promise<TaroGeneral.CallbackResult[]>;
export declare const getBoundingClientRect: (selector: string) => Promise<BoundingClientRectCallback[]>;
export declare const getImageInfo: (src: string) => Promise<Taro.getImageInfo.SuccessCallbackResult>;
export declare const setClipboardData: (data: string) => Promise<TaroGeneral.CallbackResult>;
export declare const chooseMedia: (count?: number, mediaType?: "video" | "image" | "*", sourceType?: "album" | "camera" | "*", camera?: "back" | "front") => Promise<Taro.chooseMedia.ChooseMedia[]>;
export declare const chooseMessageFile: (count?: number, type?: "video" | "image" | "file" | "all") => Promise<Taro.chooseMessageFile.ChooseFile[]>;
export declare const previewImage: (urls: string[], i?: number) => Promise<TaroGeneral.CallbackResult>;
export declare const getSystemInfo: () => Taro.getSystemInfoSync.Result;
export declare const login: () => Promise<string>;
export declare const requestPayment: (option: RequestPaymentOption) => Promise<TaroGeneral.CallbackResult>;
export declare const makePhoneCall: (phoneNumber: string) => Promise<TaroGeneral.CallbackResult>;
export declare const saveImageToPhotosAlbum: (filePath: string) => Promise<TaroGeneral.CallbackResult>;
export declare const authorize: (scope: AuthorizeScope, message: string) => Promise<never>;
